
package com.sobey.phonepublish;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PhonePublishServiceService", targetNamespace = "http://soap.sobey.com/", wsdlLocation = "http://127.0.0.1:8888/ws/phoneService?WSDL")
public class PhonePublishServiceService
    extends Service
{

    private final static URL PHONEPUBLISHSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException PHONEPUBLISHSERVICESERVICE_EXCEPTION;
    private final static QName PHONEPUBLISHSERVICESERVICE_QNAME = new QName("http://soap.sobey.com/", "PhonePublishServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8888/ws/phoneService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PHONEPUBLISHSERVICESERVICE_WSDL_LOCATION = url;
        PHONEPUBLISHSERVICESERVICE_EXCEPTION = e;
    }

    public PhonePublishServiceService() {
        super(__getWsdlLocation(), PHONEPUBLISHSERVICESERVICE_QNAME);
    }

    public PhonePublishServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PHONEPUBLISHSERVICESERVICE_QNAME, features);
    }

    public PhonePublishServiceService(URL wsdlLocation) {
        super(wsdlLocation, PHONEPUBLISHSERVICESERVICE_QNAME);
    }

    public PhonePublishServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PHONEPUBLISHSERVICESERVICE_QNAME, features);
    }

    public PhonePublishServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PhonePublishServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PhonePublishService
     */
    @WebEndpoint(name = "PhonePublishServicePort")
    public PhonePublishService getPhonePublishServicePort() {
        return super.getPort(new QName("http://soap.sobey.com/", "PhonePublishServicePort"), PhonePublishService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PhonePublishService
     */
    @WebEndpoint(name = "PhonePublishServicePort")
    public PhonePublishService getPhonePublishServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.sobey.com/", "PhonePublishServicePort"), PhonePublishService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PHONEPUBLISHSERVICESERVICE_EXCEPTION!= null) {
            throw PHONEPUBLISHSERVICESERVICE_EXCEPTION;
        }
        return PHONEPUBLISHSERVICESERVICE_WSDL_LOCATION;
    }

}
