
package com.sobey.phonepublish;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PhonePublishService", targetNamespace = "http://soap.sobey.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PhonePublishService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.sobey.phonepublish.Phone
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPhoneService", targetNamespace = "http://soap.sobey.com/", className = "com.sobey.phonepublish.GetPhoneService")
    @ResponseWrapper(localName = "getPhoneServiceResponse", targetNamespace = "http://soap.sobey.com/", className = "com.sobey.phonepublish.GetPhoneServiceResponse")
    @Action(input = "http://soap.sobey.com/PhonePublishService/getPhoneServiceRequest", output = "http://soap.sobey.com/PhonePublishService/getPhoneServiceResponse")
    public Phone getPhoneService(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
